version: '2.3'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379"
    volumes:
      - ./redis:/data
  node:
    build: .
    image: yukimochi/vrc_hls
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - redis
